export interface Review {
  id: string;
  productSlug: string;
  author: string;
  city: string;
  rating: number;
  date: string;
  title: string;
  body: string;
  verified: boolean;
  helpful: number;
  photo?: string;
}

export const REVIEWS: Review[] = [
  // ── Vermicompost ──────────────────────────────────────────────
  {
    id: "rv-vermicompost-1",
    productSlug: "vermicompost",
    author: "Ananya Krishnan",
    city: "Bengaluru",
    rating: 5,
    date: "2026-02-18",
    title: "My monstera finally pushed a new leaf",
    body: "Mixed two handfuls into the topsoil and within about ten days my monstera unfurled a fresh leaf, the first in months. Zero smell, which I honestly did not expect from compost.",
    verified: true,
    helpful: 27,
    photo: "/products/vermicompost/1.jpeg",
  },
  {
    id: "rv-vermicompost-2",
    productSlug: "vermicompost",
    author: "Rohan Deshpande",
    city: "Pune",
    rating: 5,
    date: "2026-01-09",
    title: "Soil holds water so much better now",
    body: "My terrace pots used to dry out by afternoon in summer. After working this in, the soil stays damp longer and I water less often. Feels lighter and crumblier too.",
    verified: true,
    helpful: 19,
  },
  {
    id: "rv-vermicompost-3",
    productSlug: "vermicompost",
    author: "Meera Pillai",
    city: "Kochi",
    rating: 4,
    date: "2025-12-22",
    title: "Good stuff, bag was a bit torn",
    body: "The castings themselves are lovely and truly odourless, my money plant has perked up. Only gripe is the bag arrived with a small tear so a little spilled in transit.",
    verified: true,
    helpful: 8,
  },
  {
    id: "rv-vermicompost-4",
    productSlug: "vermicompost",
    author: "Imran Sheikh",
    city: "Hyderabad",
    rating: 5,
    date: "2025-11-28",
    title: "Gentle enough for seedlings",
    body: "I was worried about burning my young chilli seedlings but this is so mild I used it right away with no issues. Everything is greener after two weeks.",
    verified: true,
    helpful: 14,
  },
  {
    id: "rv-vermicompost-5",
    productSlug: "vermicompost",
    author: "Sneha Reddy",
    city: "Chennai",
    rating: 5,
    date: "2026-03-30",
    title: "All my pots get a spoon of this now",
    body: "Became my default feed for everything from the hibiscus to the curry leaf plant. Hibiscus is throwing more buds and the leaves have a darker, healthier look.",
    verified: true,
    helpful: 22,
  },
  {
    id: "rv-vermicompost-6",
    productSlug: "vermicompost",
    author: "Karthik Nair",
    city: "Coimbatore",
    rating: 3,
    date: "2026-04-14",
    title: "Decent but I expected finer texture",
    body: "It works fine and there is genuinely no odour, my snake plant seems happy. I just found a few bits of undigested material in mine, nothing major but worth mentioning.",
    verified: false,
    helpful: 5,
  },
  {
    id: "rv-vermicompost-7",
    productSlug: "vermicompost",
    author: "Divya Menon",
    city: "Thiruvananthapuram",
    rating: 5,
    date: "2026-05-21",
    title: "Repeat buyer, never disappoints",
    body: "Third bag now. My tomatoes in grow bags respond to nothing better than this. Steady, gentle, and the plants just look well-fed without any chemical push.",
    verified: true,
    helpful: 16,
  },

  // ── Neem Cake ─────────────────────────────────────────────────
  {
    id: "rv-neem-cake-1",
    productSlug: "neem-cake",
    author: "Vikram Joshi",
    city: "Mumbai",
    rating: 5,
    date: "2026-02-02",
    title: "No more fungus gnats, finally",
    body: "I was losing the battle with gnats in my indoor pots. Worked a thin layer of neem cake into the topsoil and within two weeks the gnats were just gone. Bonus, my pothos greened up.",
    verified: true,
    helpful: 34,
    photo: "/products/neem-cake/2.jpeg",
  },
  {
    id: "rv-neem-cake-2",
    productSlug: "neem-cake",
    author: "Priya Sundaram",
    city: "Chennai",
    rating: 5,
    date: "2026-01-17",
    title: "Saved my rose bed from grubs",
    body: "Found white grubs chewing the roots of my roses. Mixed this in around the base and the new growth came back clean. Plants are flowering again with no leaf damage.",
    verified: true,
    helpful: 21,
  },
  {
    id: "rv-neem-cake-3",
    productSlug: "neem-cake",
    author: "Aditya Rao",
    city: "Hyderabad",
    rating: 4,
    date: "2025-12-05",
    title: "Works well, smell is strong",
    body: "Does exactly what it claims, the nematode problem on my tomatoes has clearly eased. Just be ready, it has a sharp neem smell for a day or two after applying. Fades though.",
    verified: true,
    helpful: 12,
  },
  {
    id: "rv-neem-cake-4",
    productSlug: "neem-cake",
    author: "Fatima Khan",
    city: "Lucknow",
    rating: 5,
    date: "2025-11-19",
    title: "Two-in-one feed and pest control",
    body: "What I like is it feeds the soil while keeping pests down, so it is doing two jobs. My curry leaf plant has put out a flush of healthy new leaves with no whitefly this time.",
    verified: true,
    helpful: 18,
  },
  {
    id: "rv-neem-cake-5",
    productSlug: "neem-cake",
    author: "Sanjay Patil",
    city: "Nagpur",
    rating: 5,
    date: "2026-03-11",
    title: "My adenium roots are healthier",
    body: "Started adding a pinch to my adenium repots to keep soil pests away. No more root nibbling, and the caudex looks firm and healthy. Will keep using at every repotting.",
    verified: true,
    helpful: 9,
  },
  {
    id: "rv-neem-cake-6",
    productSlug: "neem-cake",
    author: "Lakshmi Iyer",
    city: "Mysuru",
    rating: 4,
    date: "2026-04-27",
    title: "Effective, took patience",
    body: "It is not an overnight fix, took about three weeks to really notice fewer pests on my chillies. But it is gentle and organic so I was happy to wait. Leaves look richer green now.",
    verified: true,
    helpful: 7,
  },
  {
    id: "rv-neem-cake-7",
    productSlug: "neem-cake",
    author: "Gaurav Malhotra",
    city: "Chandigarh",
    rating: 5,
    date: "2026-05-30",
    title: "Standard in my potting routine",
    body: "Every new pot gets a spoon of this mixed in now. Keeps the soil pests off from day one and the plants establish faster. My money plant has not had a single gnat since.",
    verified: false,
    helpful: 11,
  },

  // ── Bio NPK Granules ──────────────────────────────────────────
  {
    id: "rv-bio-npk-granules-1",
    productSlug: "bio-npk-granules",
    author: "Nikhil Verma",
    city: "Delhi",
    rating: 5,
    date: "2026-02-25",
    title: "More buds on my hibiscus",
    body: "The slow-release really shows, I fed once and the hibiscus kept pushing buds for weeks instead of one flush. Knowing it is live bacteria and not a salt feed makes me feel better about it.",
    verified: true,
    helpful: 29,
    photo: "/products/bio-npk-granules/1.jpeg",
  },
  {
    id: "rv-bio-npk-granules-2",
    productSlug: "bio-npk-granules",
    author: "Shruti Agarwal",
    city: "Jaipur",
    rating: 5,
    date: "2026-01-30",
    title: "Tomatoes finally set fruit",
    body: "My tomato plants were all leaf and no fruit. Three weeks after these granules the flowering picked up and they actually set fruit. The slow feeding seems to suit them.",
    verified: true,
    helpful: 24,
  },
  {
    id: "rv-bio-npk-granules-3",
    productSlug: "bio-npk-granules",
    author: "Arjun Kapoor",
    city: "Gurugram",
    rating: 4,
    date: "2025-12-14",
    title: "Good results, slow to start",
    body: "Because it is living bacteria it takes a couple of weeks to kick in, so do not expect instant green. Once it did, my chillies flowered noticeably more. Patience pays here.",
    verified: true,
    helpful: 13,
  },
  {
    id: "rv-bio-npk-granules-4",
    productSlug: "bio-npk-granules",
    author: "Pooja Bhat",
    city: "Mangaluru",
    rating: 5,
    date: "2025-11-22",
    title: "Better fruiting on my chillies",
    body: "Used it on my balcony chilli pots and the difference in fruit set was real. Granules are easy to scatter and water in, no measuring fuss. Will reorder before the next season.",
    verified: true,
    helpful: 15,
  },
  {
    id: "rv-bio-npk-granules-5",
    productSlug: "bio-npk-granules",
    author: "Rahul Saxena",
    city: "Bhopal",
    rating: 5,
    date: "2026-03-18",
    title: "My roses are blooming bigger",
    body: "Switched my roses to this and the blooms are fuller and the bushes look vigorous. Like that it is feeding the soil life and not just dumping nutrients. Delivery was quick too.",
    verified: true,
    helpful: 10,
  },
  {
    id: "rv-bio-npk-granules-6",
    productSlug: "bio-npk-granules",
    author: "Anjali Gupta",
    city: "Indore",
    rating: 4,
    date: "2026-04-09",
    title: "Solid, wish the pack were bigger",
    body: "Happy with the flowering boost on my money plant and adenium. The only thing is the pack ran out faster than I expected across all my pots. Would buy a larger size if offered.",
    verified: false,
    helpful: 6,
  },
  {
    id: "rv-bio-npk-granules-7",
    productSlug: "bio-npk-granules",
    author: "Sandeep Kulkarni",
    city: "Thane",
    rating: 5,
    date: "2026-05-16",
    title: "Reliable slow feed",
    body: "I top-dress once a month and the plants stay steadily fed without that burnt-tip look from strong fertilisers. My curry leaf and tomatoes both responded well over the season.",
    verified: true,
    helpful: 17,
  },

  // ── Organic Cow Manure ────────────────────────────────────────
  {
    id: "rv-organic-cow-manure-1",
    productSlug: "organic-cow-manure",
    author: "Geeta Choudhary",
    city: "Ahmedabad",
    rating: 5,
    date: "2026-02-08",
    title: "Properly cured, no smell at all",
    body: "I have used cow manure before that stank up the whole balcony. This one is fully dried and weed-free, no odour and no random sprouts. Used it as a base feed and my roses love it.",
    verified: true,
    helpful: 26,
    photo: "/products/organic-cow-manure/2.jpeg",
  },
  {
    id: "rv-organic-cow-manure-2",
    productSlug: "organic-cow-manure",
    author: "Manish Tiwari",
    city: "Kanpur",
    rating: 5,
    date: "2026-01-12",
    title: "Great base mix for grow bags",
    body: "Blended this into my tomato grow bags at the start of the season and the plants took off. No weeds popping up, which used to be my biggest annoyance with raw manure.",
    verified: true,
    helpful: 20,
  },
  {
    id: "rv-organic-cow-manure-3",
    productSlug: "organic-cow-manure",
    author: "Revathi Subramanian",
    city: "Madurai",
    rating: 4,
    date: "2025-12-19",
    title: "Good all-rounder, a bit dusty",
    body: "Does a fine job as a general feed, my hibiscus and curry leaf both filled out. It is quite finely powdered so it kicks up dust when you pour it, maybe do it outdoors.",
    verified: true,
    helpful: 9,
  },
  {
    id: "rv-organic-cow-manure-4",
    productSlug: "organic-cow-manure",
    author: "Deepak Yadav",
    city: "Noida",
    rating: 5,
    date: "2025-11-15",
    title: "Weed-free as promised",
    body: "Not a single weed seedling came up, which tells me it is genuinely well composted. My money plant and snake plant are thriving on it as a base. Honest product.",
    verified: true,
    helpful: 13,
  },
  {
    id: "rv-organic-cow-manure-5",
    productSlug: "organic-cow-manure",
    author: "Kavya Shetty",
    city: "Udupi",
    rating: 5,
    date: "2026-03-25",
    title: "My go-to soil amendment",
    body: "Use it every season to refresh my pots. Sun-dried and clean, mixes in easily, and the plants get a steady all-round feed. The roses especially seem to appreciate it.",
    verified: false,
    helpful: 8,
  },
  {
    id: "rv-organic-cow-manure-6",
    productSlug: "organic-cow-manure",
    author: "Harpreet Singh",
    city: "Amritsar",
    rating: 4,
    date: "2026-04-20",
    title: "Works well, heavy bag to lug",
    body: "No complaints on quality, fully cured and easy on the plants. My chillies greened up nicely. Just a heads up it is a hefty bag, the delivery person was not thrilled with my third floor.",
    verified: true,
    helpful: 5,
  },
  {
    id: "rv-organic-cow-manure-7",
    productSlug: "organic-cow-manure",
    author: "Sunita Naik",
    city: "Visakhapatnam",
    rating: 5,
    date: "2026-05-27",
    title: "Reliable base feed every time",
    body: "Been buying this for a year. Consistent quality, always dry and weed-free, and my whole terrace garden runs on it as the base. The adenium and hibiscus are blooming steadily.",
    verified: true,
    helpful: 14,
  },

  // ── Rock Phosphate ────────────────────────────────────────────
  {
    id: "rv-rock-phosphate-1",
    productSlug: "rock-phosphate",
    author: "Tarun Menon",
    city: "Kozhikode",
    rating: 5,
    date: "2026-02-14",
    title: "Stronger roots, then a flush of blooms",
    body: "Worked this into my rose bed in winter and by spring the root system was clearly stronger and the bushes put out a heavy flush of flowers. The slow phosphorus really does its thing.",
    verified: true,
    helpful: 23,
    photo: "/products/rock-phosphate/1.jpeg",
  },
  {
    id: "rv-rock-phosphate-2",
    productSlug: "rock-phosphate",
    author: "Bhavna Desai",
    city: "Surat",
    rating: 5,
    date: "2026-01-23",
    title: "Set it and forget it for the season",
    body: "Like that it releases slowly so I mix it in once and it feeds for months. My tomatoes set fruit better and the plants stand sturdier, I think the calcium helps too.",
    verified: true,
    helpful: 16,
  },
  {
    id: "rv-rock-phosphate-3",
    productSlug: "rock-phosphate",
    author: "Yusuf Ansari",
    city: "Bhopal",
    rating: 4,
    date: "2025-12-09",
    title: "Patience needed but worth it",
    body: "This is a slow mineral feed, so do not expect quick results. Months in, my hibiscus rooted strongly and bloomed more. If you want instant green this is not it, but for the long game it works.",
    verified: true,
    helpful: 11,
  },
  {
    id: "rv-rock-phosphate-4",
    productSlug: "rock-phosphate",
    author: "Padma Rao",
    city: "Vijayawada",
    rating: 5,
    date: "2025-11-26",
    title: "My adenium caudex bulked up",
    body: "Added it at repotting and over a few months the adenium developed a thicker caudex and stronger roots, then started flowering. Natural mineral, no salt buildup in the pot.",
    verified: false,
    helpful: 9,
  },
  {
    id: "rv-rock-phosphate-5",
    productSlug: "rock-phosphate",
    author: "Vivek Chauhan",
    city: "Dehradun",
    rating: 5,
    date: "2026-03-05",
    title: "Foundation feed for my fruiting pots",
    body: "I now add this to every fruiting plant at planting time. The chillies and tomatoes root deeper and the fruiting is more consistent. A little goes a long way given how slow it releases.",
    verified: true,
    helpful: 12,
  },
  {
    id: "rv-rock-phosphate-6",
    productSlug: "rock-phosphate",
    author: "Sarita Bose",
    city: "Kolkata",
    rating: 4,
    date: "2026-04-17",
    title: "Good product, gritty texture",
    body: "Does build strong roots, my roses are proof. It is quite gritty and powdery so wear gloves when mixing. Once in the soil it works quietly in the background which I like.",
    verified: true,
    helpful: 6,
  },
  {
    id: "rv-rock-phosphate-7",
    productSlug: "rock-phosphate",
    author: "Mohan Pillai",
    city: "Thrissur",
    rating: 5,
    date: "2026-05-12",
    title: "Roots first, blooms followed",
    body: "Exactly as described, the plants spent the first weeks building roots and then the money plant and hibiscus rewarded me with vigorous growth. Will keep it as my base phosphorus source.",
    verified: true,
    helpful: 15,
  },

  // ── Potting Mix ───────────────────────────────────────────────
  {
    id: "rv-potting-mix-1",
    productSlug: "potting-mix",
    author: "Ritika Sharma",
    city: "Jaipur",
    rating: 5,
    date: "2026-02-21",
    title: "Light, airy, ready to use",
    body: "Opened the bag and potted straight away, no mixing needed. It is so light and drains beautifully, my monstera roots love it. No more soggy compacted soil at the bottom of the pot.",
    verified: true,
    helpful: 31,
    photo: "/products/potting-mix/2.jpeg",
  },
  {
    id: "rv-potting-mix-2",
    productSlug: "potting-mix",
    author: "Abhishek Reddy",
    city: "Warangal",
    rating: 5,
    date: "2026-01-06",
    title: "Repotted everything in this",
    body: "Did a big repotting weekend with this mix for my whole indoor collection. The cocopeat and aeration blend keeps it fluffy and water runs through cleanly. Plants settled with no transplant shock.",
    verified: true,
    helpful: 22,
  },
  {
    id: "rv-potting-mix-3",
    productSlug: "potting-mix",
    author: "Nandini Hegde",
    city: "Hubballi",
    rating: 4,
    date: "2025-12-28",
    title: "Lovely mix, needed extra feed later",
    body: "Texture is perfect, airy and well draining, my snake plant is happy. Just note it is a light blend so I added some compost after a month for heavier feeders like tomatoes.",
    verified: true,
    helpful: 10,
  },
  {
    id: "rv-potting-mix-4",
    productSlug: "potting-mix",
    author: "Faizal Rahman",
    city: "Kannur",
    rating: 5,
    date: "2025-11-13",
    title: "No more root rot in my succulents",
    body: "My old soil held too much water and I kept losing plants. This drains fast enough that even my money plant cuttings rooted without rotting. Such a difference in texture.",
    verified: true,
    helpful: 18,
  },
  {
    id: "rv-potting-mix-5",
    productSlug: "potting-mix",
    author: "Swati Kulkarni",
    city: "Solapur",
    rating: 5,
    date: "2026-03-29",
    title: "Seedlings love this",
    body: "Started my chilli and tomato seedlings in this and germination was great. The mix is soft enough for delicate roots to push through, and it never crusts over on top.",
    verified: false,
    helpful: 13,
  },
  {
    id: "rv-potting-mix-6",
    productSlug: "potting-mix",
    author: "Joseph Mathew",
    city: "Kottayam",
    rating: 4,
    date: "2026-04-22",
    title: "Great mix, bag a touch dry",
    body: "Works lovely once moistened, very airy. Mine arrived quite dry and dusty so I had to wet it down well before potting, after that it was perfect for my curry leaf transplant.",
    verified: true,
    helpful: 7,
  },
  {
    id: "rv-potting-mix-7",
    productSlug: "potting-mix",
    author: "Aishwarya Nair",
    city: "Ernakulam",
    rating: 5,
    date: "2026-05-19",
    title: "My default for every pot now",
    body: "Stopped making my own mix, this saves the effort and performs better. Light, drains well, and my hibiscus and adenium have not looked back. Consistent bag after bag.",
    verified: true,
    helpful: 16,
  },

  // ── Perlite ───────────────────────────────────────────────────
  {
    id: "rv-perlite-1",
    productSlug: "perlite",
    author: "Siddharth Bose",
    city: "Kolkata",
    rating: 5,
    date: "2026-02-27",
    title: "Goodbye root rot",
    body: "Mixed a generous amount into my succulent pots and the drainage transformed. No more mushy stems, my adenium and snake plant are firm and healthy through the monsoon now.",
    verified: true,
    helpful: 28,
    photo: "/products/perlite/2.jpeg",
  },
  {
    id: "rv-perlite-2",
    productSlug: "perlite",
    author: "Tanvi Joshi",
    city: "Vadodara",
    rating: 5,
    date: "2026-01-19",
    title: "Perfect for seed-starting",
    body: "Cut my seed mix with this and the aeration helped my tomato and chilli seeds sprout strong without damping off. Such a clean, light material to work with.",
    verified: true,
    helpful: 17,
  },
  {
    id: "rv-perlite-3",
    productSlug: "perlite",
    author: "Rakesh Pawar",
    city: "Aurangabad",
    rating: 4,
    date: "2025-12-11",
    title: "Does the job, very dusty",
    body: "Great for opening up heavy soil, my monstera drains far better now. Fair warning it is dusty, dampen it lightly before mixing or you will be coughing. Otherwise excellent.",
    verified: true,
    helpful: 12,
  },
  {
    id: "rv-perlite-4",
    productSlug: "perlite",
    author: "Lubna Qureshi",
    city: "Bhopal",
    rating: 5,
    date: "2025-11-21",
    title: "Saved my overwatered money plant",
    body: "I tend to overwater so I added plenty of perlite to my mix. Now the excess drains away instead of drowning the roots. My money plant has bounced right back and is vining again.",
    verified: false,
    helpful: 14,
  },
  {
    id: "rv-perlite-5",
    productSlug: "perlite",
    author: "Ganesh Kumar",
    city: "Salem",
    rating: 5,
    date: "2026-03-13",
    title: "Essential for my succulent mixes",
    body: "I no longer make a cactus or succulent mix without it. The aeration keeps roots breathing and rot at bay. My adenium collection has never been healthier through the wet season.",
    verified: true,
    helpful: 10,
  },
  {
    id: "rv-perlite-6",
    productSlug: "perlite",
    author: "Megha Reddy",
    city: "Guntur",
    rating: 5,
    date: "2026-04-25",
    title: "Light bag, big difference",
    body: "Such a lightweight bag for the volume, and a little transforms a dense potting soil. My roses and hibiscus stopped sulking once their pots actually drained properly.",
    verified: true,
    helpful: 9,
  },
  {
    id: "rv-perlite-7",
    productSlug: "perlite",
    author: "Alok Nanda",
    city: "Bhubaneswar",
    rating: 4,
    date: "2026-05-08",
    title: "Works great, floats when watering",
    body: "Excellent for drainage and aeration, no complaints there. One quirk, some pieces float to the top when I water from above, so I top with a little soil. My snake plant loves the airy mix.",
    verified: true,
    helpful: 6,
  },

  // ── Epsom Salt ────────────────────────────────────────────────
  {
    id: "rv-epsom-salt-1",
    productSlug: "epsom-salt",
    author: "Neha Bansal",
    city: "Chandigarh",
    rating: 5,
    date: "2026-02-11",
    title: "Yellowing leaves greened up fast",
    body: "My rose leaves had that yellow between the veins. One foliar spray of this dissolved in water and within a week or so the green came back deeper and richer. Genuinely impressed.",
    verified: true,
    helpful: 30,
    photo: "/products/epsom-salt/1.jpeg",
  },
  {
    id: "rv-epsom-salt-2",
    productSlug: "epsom-salt",
    author: "Suresh Babu",
    city: "Tirupati",
    rating: 5,
    date: "2026-01-15",
    title: "Fixed my tomato leaf yellowing",
    body: "Classic magnesium deficiency on my tomatoes, lower leaves going yellow between the veins. A drench sorted it out and the new growth is a healthy dark green. Cheap and effective.",
    verified: true,
    helpful: 19,
  },
  {
    id: "rv-epsom-salt-3",
    productSlug: "epsom-salt",
    author: "Ishita Banerjee",
    city: "Siliguri",
    rating: 4,
    date: "2025-12-17",
    title: "Helps, do not overdo it",
    body: "Worked nicely on my hibiscus interveinal yellowing, leaves deepened in colour. Just a caution, more is not better with this, I went heavy once and stuck to the recommended dose after.",
    verified: true,
    helpful: 11,
  },
  {
    id: "rv-epsom-salt-4",
    productSlug: "epsom-salt",
    author: "Mohammed Asif",
    city: "Kalaburagi",
    rating: 5,
    date: "2025-11-17",
    title: "Deeper green on my curry leaf",
    body: "My curry leaf plant looked pale and tired. A monthly foliar spray of this and the leaves are a glossy dark green again, and more fragrant when I cook with them. Dissolves clean in water.",
    verified: false,
    helpful: 13,
  },
  {
    id: "rv-epsom-salt-5",
    productSlug: "epsom-salt",
    author: "Pallavi Shinde",
    city: "Kolhapur",
    rating: 5,
    date: "2026-03-22",
    title: "My monstera colour is back",
    body: "The newer monstera leaves were coming out a bit washed out. A gentle drench with this fixed the magnesium gap and the colour is rich again. Easy to use, just dissolve and water in.",
    verified: true,
    helpful: 8,
  },
  {
    id: "rv-epsom-salt-6",
    productSlug: "epsom-salt",
    author: "Ramesh Gowda",
    city: "Tumakuru",
    rating: 3,
    date: "2026-04-29",
    title: "Did help but slower than I hoped",
    body: "It did green up my chillies eventually but it took a few weeks of weekly sprays, not the quick fix some reviews suggest. Works, just manage expectations. Packaging was fine.",
    verified: true,
    helpful: 5,
  },
  {
    id: "rv-epsom-salt-7",
    productSlug: "epsom-salt",
    author: "Anita Thomas",
    city: "Alappuzha",
    rating: 5,
    date: "2026-05-24",
    title: "Keep a pack on hand always",
    body: "Whenever I spot interveinal yellowing on any plant I reach for this. Fixed my money plant and roses both. A pack lasts ages since you use so little per spray. Reliable.",
    verified: true,
    helpful: 12,
  },

  // ── Flower Booster ────────────────────────────────────────────
  {
    id: "rv-flower-booster-1",
    productSlug: "flower-booster",
    author: "Kabir Malhotra",
    city: "Delhi",
    rating: 5,
    date: "2026-02-16",
    title: "My roses are covered in blooms",
    body: "The high-potassium formula really delivers, my rose bushes set far more buds and the flowers last noticeably longer in the vase. Started seeing extra buds within about two weeks.",
    verified: true,
    helpful: 33,
    photo: "/products/flower-booster/1.jpeg",
  },
  {
    id: "rv-flower-booster-2",
    productSlug: "flower-booster",
    author: "Sneha Kamath",
    city: "Mangaluru",
    rating: 5,
    date: "2026-01-27",
    title: "Hibiscus blooming nonstop",
    body: "My hibiscus went from the odd flower to blooming almost daily after I started this. The blooms are bigger too. I feed it fortnightly during the warm months now.",
    verified: true,
    helpful: 21,
  },
  {
    id: "rv-flower-booster-3",
    productSlug: "flower-booster",
    author: "Varun Pillai",
    city: "Kollam",
    rating: 4,
    date: "2025-12-03",
    title: "More buds, slightly fiddly to measure",
    body: "Definitely got more buds on my adenium and the flowers held longer. The only minor thing is measuring the dose precisely each time is a bit fiddly, a scoop in the pack would help.",
    verified: true,
    helpful: 10,
  },
  {
    id: "rv-flower-booster-4",
    productSlug: "flower-booster",
    author: "Deepika Rao",
    city: "Davangere",
    rating: 5,
    date: "2025-11-24",
    title: "Bigger, longer-lasting blooms",
    body: "Used it on my balcony roses and hibiscus before the festive season and they were loaded with flowers that did not drop quickly. The potassium boost is clearly doing its job.",
    verified: false,
    helpful: 15,
  },
  {
    id: "rv-flower-booster-5",
    productSlug: "flower-booster",
    author: "Rajat Khurana",
    city: "Ludhiana",
    rating: 5,
    date: "2026-03-08",
    title: "Turned my shy bloomer around",
    body: "My adenium would barely flower. A few rounds of this and it set a cluster of buds that opened into big lasting blooms. So pleased I bought a second pack already.",
    verified: true,
    helpful: 12,
  },
  {
    id: "rv-flower-booster-6",
    productSlug: "flower-booster",
    author: "Manjula Naidu",
    city: "Nellore",
    rating: 2,
    date: "2026-04-12",
    title: "Did not see much change for me",
    body: "Followed the directions on my hibiscus for over a month and only saw a small bump in flowering. Maybe my plant had other issues, but for me the effect was modest. Delivery was prompt though.",
    verified: true,
    helpful: 4,
  },
  {
    id: "rv-flower-booster-7",
    productSlug: "flower-booster",
    author: "Prakash Iyer",
    city: "Madurai",
    rating: 5,
    date: "2026-05-26",
    title: "My bloom-season staple",
    body: "Every flowering season this comes out. The roses and hibiscus respond with masses of buds and the colour is intense. Long-lasting blooms mean my balcony stays full of flowers for weeks.",
    verified: true,
    helpful: 18,
  },
];

export function reviewsForSlug(slug: string): Review[] {
  return REVIEWS.filter((r) => r.productSlug === slug).sort((a, b) =>
    b.date.localeCompare(a.date)
  );
}

export function ratingSummary(slug: string): {
  average: number;
  count: number;
  distribution: Record<number, number>;
} {
  const list = REVIEWS.filter((r) => r.productSlug === slug);
  const distribution: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
  let total = 0;
  for (const r of list) {
    distribution[r.rating] = (distribution[r.rating] ?? 0) + 1;
    total += r.rating;
  }
  const count = list.length;
  const average = count === 0 ? 0 : Math.round((total / count) * 10) / 10;
  return { average, count, distribution };
}

export const SITE_TESTIMONIALS: Review[] = [
  REVIEWS.find((r) => r.id === "rv-vermicompost-1")!,
  REVIEWS.find((r) => r.id === "rv-neem-cake-1")!,
  REVIEWS.find((r) => r.id === "rv-flower-booster-1")!,
  REVIEWS.find((r) => r.id === "rv-potting-mix-1")!,
  REVIEWS.find((r) => r.id === "rv-epsom-salt-1")!,
  REVIEWS.find((r) => r.id === "rv-perlite-1")!,
  REVIEWS.find((r) => r.id === "rv-bio-npk-granules-2")!,
  REVIEWS.find((r) => r.id === "rv-organic-cow-manure-1")!,
];
